language: node_js
node_js:
  - "node"
script:
  - npm test

before_script:
  - npm install
  - npm install -g grunt

# Send coverage data to Coveralls
after_script: cat ./coverage/**/lcov.info | ./node_modules/coveralls/bin/coveralls.js