env:
- HOME=desktop

language: node_js

node_js:
  - "6.6.0"

script:
  - npm test

services:
  - mongodb

before_script:
  - npm install
  - npm install -g grunt

# Send coverage data to Coveralls
after_script:
  - sleep 15
  - cat ./coverage/**/*.info | ./node_modules/coveralls/bin/coveralls.js